feature/raic-317-calendar-redesign
vora/rai-website pull request #1
Opened 2021-10-07 21:39 UTC by MitchellShimko

2021-10-08 14:02 UTC, Philip-Loeffler commented
I would reach out to Riikka concerning the links on the footer. Currently the do not go anywhere. If she has specific routes that they should head to let's add them. If not, all good.

2021-10-08 16:10 UTC, ONeill45 requested changes

2021-10-08 16:10 UTC, ONeill45 commented on src/components/Header/Header.tsx
> +        backgroundImage: `url(/image/header.png)`,
Doesn't look like the filepath for the image leads anywhere

2021-10-08 16:10 UTC, ONeill45 commented on src/templates/calendar.tsx
> +      tabName: "Events",
I'd add `cursor: pointer` on the tabs

2021-10-08 16:10 UTC, ONeill45 commented on src/components/Navigation/Navigation.tsx
> +import { AnthemLogo } from "../AnthemLogo/AnthemLogo";
use the alias path `@/components/AnthemLogo` whenever possible instead of relative paths

2021-10-08 17:38 UTC, Philip-Loeffler approved these changes

2021-10-11 20:12 UTC, ONeill45 commented on src/components/Header/Header.module.css
> +  background-image: url(./header.png);
Add `background-repeat` and `background-size` properties to this: 
![image](https://user-images.githubusercontent.com/13375042/136849802-521d95b7-43b8-4a1b-9033-b13117fae7f8.png)

Right now the image is repeating and has a clear line break down the middle

2021-10-11 20:19 UTC, closed without merging